apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-operator-ui.fullname" .}}--config
  labels:
{{ include "hlf-operator-ui.labels" . | indent 4 }}
data:
  config.json: |
    {
      "apiUrl": "{{ .Values.apiUrl }}",
      "logoUrl": "{{ .Values.logoUrl }}",
      "oidcAuthority": "{{ .Values.auth.oidcAuthority }}",
      "oidcClientId": "{{ .Values.auth.oidcClientId }}",
      "oidcScope": "{{ .Values.auth.oidcScope }}"
    }
