{{- if and (not .Values.istio.hosts) .Values.gatewayApi.hosts -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "hlf-ca.fullname" . }}-tlsroute
spec:
  parentRefs:
    - name: {{ include "hlf-ca.fullname" . }}-gateway
      sectionName: tcp
  hostnames:
  {{- range .Values.gatewayApi.hosts }}
      - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "hlf-ca.fullname" . }}
          port: 7054
{{- end -}}
