{{- $fullName := include "fabric-operations-console.fullname" . -}}
{{- $serviceName :=  printf "%s--%s" $fullName "couchdb" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fabric-operations-console.fullname" . }}
  labels:
  {{- include "fabric-operations-console.labels" . | nindent 4 }}
data:
  DB_CONNECTION_STRING: {{ (printf "http://%s:%s@%s:5984" .Values.couchdb.username  .Values.couchdb.password $serviceName )   | b64enc }}
  DB_SYSTEM: {{ "athena_system" | b64enc }}
  CONFIGURE_FILE: {{ "/config/config.yaml" | b64enc}}
