apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fabric-operations-console.fullname" . }}--couchdb
  labels:
{{ include "fabric-operations-console.labels" . | indent 4 }}
type: Opaque
data:
  COUCHDB_USER:  {{ .Values.couchdb.username | b64enc | quote }}
  COUCHDB_PASSWORD:  {{ .Values.couchdb.password | b64enc | quote }}