apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-operations-console.fullname" . }}--couchdb
  labels:
    {{- include "fabric-operations-console.couchDBLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5984
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fabric-operations-console.couchDBselectorLabels" . | nindent 4 }}
