{{- if and .Values.proxy.enabled .Values.proxy.istio.hosts  -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}-virtualservice-proxy
spec:
  hosts:
    {{- range .Values.proxy.istio.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - {{ include "hlf-ordnode.fullname" . }}-gateway-proxy
  tls:
    - match:
        - port: 443
          sniHosts:
          {{- range .Values.proxy.istio.hosts }}
              - {{ . }}
          {{- end }}
      route:
        - destination:
            host: {{ include "hlf-ordnode.fullname" . }}
            port:
              number: 7443

{{- end -}}
