{{- if and .Values.channelParticipationEnabled (and (not .Values.adminIstio.hosts) .Values.adminGatewayApi.hosts)  -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}-tlsroute-admin
spec:
  parentRefs:
    - name: {{ include "hlf-ordnode.fullname" . }}-gateway-admin
      sectionName: tcp
  hostnames:
  {{- range .Values.adminGatewayApi.hosts }}
      - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "hlf-ordnode.fullname" . }}
          port: 7053
{{- end -}}
