{{- if and .Values.channelParticipationEnabled (and (not .Values.adminIstio.hosts) (and (.Values.adminGatewayApi.hosts) (.Values.adminGatewayApi.gatewayName)))  -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}-tlsroute-admin
spec:
  parentRefs:
    - name: {{.Values.adminGatewayApi.gatewayName}}
      sectionName: tcp
      namespace: {{.Values.gatewayApi.gatewayNamespace}}
  hostnames:
  {{- range .Values.adminGatewayApi.hosts }}
      - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "hlf-ordnode.fullname" . }}
          port: 7053
{{- end -}}
