apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hlf
spec:
  version: "v1.5.1"
  homepage: https://github.com/kfsoftware/hlf-operator
  shortDescription: "Deploy and manage Hyperledger Fabric Peers, Orderers and Certificate authorities"
  description: |
    The kubectl-hlf plugin wraps the Hyperledger Fabric Operator and provides a simple
    interface to create and manage Hyperledger Fabric Peers, Orderers and Certificate authorities
  caveats: |
    * For resources that are not in default namespace, currently you must
      specify -n/--namespace explicitly (the current namespace setting is not
      yet used).
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/kfsoftware/hlf-operator/releases/download/v1.5.1/kubectl-hlf_1.5.1_darwin_amd64.zip
      sha256: 814af545e60b7f28f283666e0bd1b5af1c6513b7d8045e12d4d8e15e88465595
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/kfsoftware/hlf-operator/releases/download/v1.5.1/kubectl-hlf_1.5.1_linux_amd64.zip
      sha256: 80b8f1ff873fe1363a75ccf31236867252d61c2f2ff3ca0f68859c944401824e
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/kfsoftware/hlf-operator/releases/download/v1.5.1/kubectl-hlf_1.5.1_windows_amd64.zip
      sha256: d35ae9c9be11c12f049074694eccfb4ef40a986eb509efacd4d8a70a72f24b65
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: freebsd
          arch: amd64
      uri: https://github.com/kfsoftware/hlf-operator/releases/download/v1.5.1/kubectl-hlf_1.5.1_linux_amd64.zip
      sha256: 69846ea653fc8ffc74971fa3689ac9a95a3aff3e840c59bb49ae7f653e4f9f11
      bin: kubectl-hlf
