image:
  repository: hyperledger/fabric-peer
  tag: amd64-2.2.0
  pullPolicy: IfNotPresent

istio:
  port: 443
  hosts: []
  ingressGateway: ingressgateway

dockerSocketPath: /var/run/docker.sock

ingress:
  enabled: false
  annotations: { }
  path: /
  hosts:
    - hlf-peer.local
  tls: [ ]

rbac:
  ns: default
##################################
## Peer configuration options    #
##################################
peer:
  # Type of database ("goleveldb" or "CouchDB"):
  databaseType: goleveldb
  ## MSP ID of the Peer
  mspID: Org1MSP
  gossip:
    bootstrap: ""
    endpoint: ""
    externalEndpoint: ""
    orgLeader: "false"
    useLeaderElection: "true"

  tls:
    server:
      enabled: "true"
    client:
      enabled: "false"


# Certificate: as 'cert.pem'
cert: |
  -----BEGIN CERTIFICATE-----
  MIICiDCCAi6gAwIBAgIUJyTfF3b/G/YYt3QAM4HVVVXIaCUwCgYIKoZIzj0EAwIw
  bDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRcwFQYDVQQK
  Ew5vcmcxLmxvY2FsaG9zdDEPMA0GA1UECxMGRmFicmljMRowGAYDVQQDExFjYS5v
  cmcxLmxvY2FsaG9zdDAeFw0yMDA4MzAxOTIwMDBaFw0yMTA4MzAxOTI1MDBaMDAx
  DTALBgNVBAsTBHBlZXIxHzAdBgNVBAMTFmxsYXJhd3NnbXd5cWZha2hndnhhd2Ew
  WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASaM4fhUp35Jz0ib0Sbfktw36c31UuX
  4S+qycOzWVQH+SotJB6CJnsXVeLrVCVVItcXQtAn84j6Zzg+sdHcxrBSo4HpMIHm
  MA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTkWHijUbO3
  as32+CdatD2kaRpDjTArBgNVHSMEJDAigCDTOcVfuK2stRpyG/wDw1xWeL3DNuSF
  k1Q48PqzxwnpqjARBgNVHREECjAIggZkdmllam8wZwYIKgMEBQYHCAEEW3siYXR0
  cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIiLCJoZi5FbnJvbGxtZW50SUQiOiJsbGFy
  YXdzZ213eXFmYWtoZ3Z4YXdhIiwiaGYuVHlwZSI6InBlZXIifX0wCgYIKoZIzj0E
  AwIDSAAwRQIhAJf2964pLsHwNxoZJb180tVSEZVpRlhSTTia6wCragCBAiAaEm/Q
  bhoyopqU8UOgdN7DSU+IYif94bOa4jJlmWNXpQ==
  -----END CERTIFICATE-----

# Private key: as 'key.pem'
key: |
  -----BEGIN PRIVATE KEY-----
  MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg6F65FC/+rKWRa04a
  7dzX2u6gtQk5CZg+o8iwBHhv9myhRANCAASaM4fhUp35Jz0ib0Sbfktw36c31UuX
  4S+qycOzWVQH+SotJB6CJnsXVeLrVCVVItcXQtAn84j6Zzg+sdHcxrBS
  -----END PRIVATE KEY-----
hosts:
  - 192.168.39.172
  - peer0.org1.example.com

# TLS secret: as 'tls.crt' and 'tls.key'
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIICtTCCAlugAwIBAgIUG1y/UfL3IKKwR0Uviq/2Qt5AwKMwCgYIKoZIzj0EAwIw
    bDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRcwFQYDVQQK
    Ew5vcmcxLmxvY2FsaG9zdDEPMA0GA1UECxMGRmFicmljMRowGAYDVQQDExFjYS5v
    cmcxLmxvY2FsaG9zdDAeFw0yMDA4MzAxOTIwMDBaFw0yMTA4MzAxOTI1MDBaMDAx
    DTALBgNVBAsTBHBlZXIxHzAdBgNVBAMTFnFsdGNhdG1ldHdkYWxwbnBhYmFzYWcw
    WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQwkLHwXb1YUetEtJYDYaqVicHeEmYD
    CdYzrQEu1aEXcLNBPQUlc10OhCiZVyCYVlKb02wJpXyTBPAQpTKLNy3Fo4IBFTCC
    AREwDgYDVR0PAQH/BAQDAgOoMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBT8rr3D5twx+9bogS0KzlTXJgsQsTAr
    BgNVHSMEJDAigCDTOcVfuK2stRpyG/wDw1xWeL3DNuSFk1Q48PqzxwnpqjAdBgNV
    HREEFjAUghJwZWVyMC1ubi5sb2NhbGhvc3QwZwYIKgMEBQYHCAEEW3siYXR0cnMi
    OnsiaGYuQWZmaWxpYXRpb24iOiIiLCJoZi5FbnJvbGxtZW50SUQiOiJxbHRjYXRt
    ZXR3ZGFscG5wYWJhc2FnIiwiaGYuVHlwZSI6InBlZXIifX0wCgYIKoZIzj0EAwID
    SAAwRQIhAL6rDsTeybyJ/aRHRRYi1SB/4x69onV0WDDJY2fg1PG8AiAVFA32tN9C
    prbgd+aEF/TEYfqB2U3l8+Mn4x2gB3cvmw==
    -----END CERTIFICATE-----

  key: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgGA7JQ7M1NIh9rUeG
    NvmizMpmB5M55epHFCWSieyTslyhRANCAAQwkLHwXb1YUetEtJYDYaqVicHeEmYD
    CdYzrQEu1aEXcLNBPQUlc10OhCiZVyCYVlKb02wJpXyTBPAQpTKLNy3F
    -----END PRIVATE KEY-----
#
#intCACert: ""
#intCACert: |
#  -----BEGIN CERTIFICATE-----
#  MIIDyjCCAbKgAwIBAgIUfAOjdL2u+bl+pWqRNnA5gaKDGxkwDQYJKoZIhvcNAQEL
#  BQAwLzERMA8GA1UEChMIT3JnMTBNU1AxDTALBgNVBAsTBFRlY2gxCzAJBgNVBAMT
#  AmNhMB4XDTIxMDUwMzEwMTUzOVoXDTI2MDUwMjEwMTYwOVowdTEWMBQGA1UEBhMN
#  VW5pdGVkIFN0YXRlczERMA8GA1UECBMIRGVsYXdhcmUxETAPBgNVBAcTCERlbGF3
#  YXJlMRkwFwYDVQQKExBBcmlzZSBUZWNobm9sb2d5MQ0wCwYDVQQLEwR0ZWNoMQsw
#  CQYDVQQDEwJjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGVqnon8SbZ8qFe1
#  13jSO7daVK2gmKcgkK3t/pH5A4t0EhFdWNDz2OJ/M2dLyh8AXlADHNcxX3TC0scm
#  U+AQCzijYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
#  DgQWBBTDMgCPz/7v7lsBplcHPIHDunu6fTAfBgNVHSMEGDAWgBSG3tV1ToKkeByN
#  QWf73XxKCaeG4DANBgkqhkiG9w0BAQsFAAOCAgEAT5sj8zhAb0ZgcZI8j5tLZllv
#  hDCKwuG3vdPYaArtI3t7+Qm++g4oJdvnKNlpxeM5rDV1vLqZuKVhrif1b3atzs2Y
#  H98DOnpqgg8qgDZwH/Qnawz9X81FCZjewGNztT9xIbIec+1uwy+h0tntAnSryUFM
#  y3tmnpjemyu6U9Pt7j6aYE9dz5ZUGu/vECMPGke9gOtK5wR7EmpVYSycygplMz/9
#  y7+XTg8u0dIOGeCpbkZOpWQfzwpyHa/Z+P8aMQvZWtbcb1Ntg7BNGnh8yRoOvfJP
#  NLqjgstHuyWVg04YbZfq9nVjQ3xYSQsIZvDpoEfpNs2GTLxhrr7ZhHX+27lfud14
#  eddD4O+PfX7nZo+I+Xm1CZusxT/7LSnRl3govt/CYgzCiTDmW3zxg9q63FnQxbeh
#  9/8U7Daj7TJbVmjZSmsAXG5dr2oAbbiGCMGTqS0CzxyMamhyN5qcEBofWxh7p3Qp
#  I41iXK2oQdl8dzJn8BmHvkiUWnM0l75mm50WCVfu4elO4mMGejXA6H2PudV5fZ7f
#  lyWN19V+82aDzueiYAItJZztLNWOCt2fjYljww5dV+JJPjoQRwpUd8iFNdItnR71
#  7MVPyoMjCKo3uEr9pi01vKThztWxia6iOZv1mchladzgOJjLQEq6j+vhi7FceBuh
#  MkUBqd/Rg4yotw+WEac=
#  -----END CERTIFICATE-----

# CA Cert: as 'cacert.pem'
cacert: |
  -----BEGIN CERTIFICATE-----
  MIICJTCCAcqgAwIBAgIQUuFqAtZPiddn6WGnSJkzDjAKBggqhkjOPQQDAjBsMQsw
  CQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFzAVBgNVBAoTDm9y
  ZzEubG9jYWxob3N0MQ8wDQYDVQQLEwZGYWJyaWMxGjAYBgNVBAMTEWNhLm9yZzEu
  bG9jYWxob3N0MB4XDTIwMDgzMDE5MDYwOVoXDTMwMDgzMDE5MDYwOVowbDELMAkG
  A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRcwFQYDVQQKEw5vcmcx
  LmxvY2FsaG9zdDEPMA0GA1UECxMGRmFicmljMRowGAYDVQQDExFjYS5vcmcxLmxv
  Y2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEcGZyRpFnU078kCDa68
  C6TxpZG980zxbVR/wpzfg4Urj3E0Qjr+xoUoXROy5WEhO/0AOUhsSWDOSmV6tzYK
  r4ujTjBMMA4GA1UdDwEB/wQEAwIBpjAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQi
  BCDTOcVfuK2stRpyG/wDw1xWeL3DNuSFk1Q48PqzxwnpqjAKBggqhkjOPQQDAgNJ
  ADBGAiEA9QJ4AlRTpXgfOoEhRVqc0Pu6y13uWfTHdyScr4eLlJwCIQD1h1C+PdYW
  oRFWxr6uC0xDev2/rnwz01gHosiUzyg3eg==
  -----END CERTIFICATE-----

# TLS root CA certificate: as 'cert.pem'
tlsrootcert: |
  -----BEGIN CERTIFICATE-----
  MIICJTCCAcqgAwIBAgIQUuFqAtZPiddn6WGnSJkzDjAKBggqhkjOPQQDAjBsMQsw
  CQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFzAVBgNVBAoTDm9y
  ZzEubG9jYWxob3N0MQ8wDQYDVQQLEwZGYWJyaWMxGjAYBgNVBAMTEWNhLm9yZzEu
  bG9jYWxob3N0MB4XDTIwMDgzMDE5MDYwOVoXDTMwMDgzMDE5MDYwOVowbDELMAkG
  A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRcwFQYDVQQKEw5vcmcx
  LmxvY2FsaG9zdDEPMA0GA1UECxMGRmFicmljMRowGAYDVQQDExFjYS5vcmcxLmxv
  Y2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEcGZyRpFnU078kCDa68
  C6TxpZG980zxbVR/wpzfg4Urj3E0Qjr+xoUoXROy5WEhO/0AOUhsSWDOSmV6tzYK
  r4ujTjBMMA4GA1UdDwEB/wQEAwIBpjAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQi
  BCDTOcVfuK2stRpyG/wDw1xWeL3DNuSFk1Q48PqzxwnpqjAKBggqhkjOPQQDAgNJ
  ADBGAiEA9QJ4AlRTpXgfOoEhRVqc0Pu6y13uWfTHdyScr4eLlJwCIQD1h1C+PdYW
  oRFWxr6uC0xDev2/rnwz01gHosiUzyg3eg==
  -----END CERTIFICATE-----
#
#intTLSCACert: |
#  -----BEGIN CERTIFICATE-----
#  MIIDzTCCAbWgAwIBAgIUBAjpFIRfdzyrcLOgjbCDVb6nWCgwDQYJKoZIhvcNAQEL
#  BQAwMjERMA8GA1UEChMIT3JnMTBNU1AxDTALBgNVBAsTBFRlY2gxDjAMBgNVBAMT
#  BXRsc2NhMB4XDTIxMDUwMzEwMTU0MFoXDTI2MDUwMjEwMTYxMFowdTEWMBQGA1UE
#  BhMNVW5pdGVkIFN0YXRlczERMA8GA1UECBMIRGVsYXdhcmUxETAPBgNVBAcTCERl
#  bGF3YXJlMRkwFwYDVQQKExBBcmlzZSBUZWNobm9sb2d5MQ0wCwYDVQQLEwR0ZWNo
#  MQswCQYDVQQDEwJjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABI7nE6jWCDC8
#  QQSBcQx4MEgmk3vfW2wlZsJ1HkJB/3DkiYe/PO2vATOrx5agKe+Mtl5n1Sx+0yKU
#  SGCK1L9tV82jYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0G
#  A1UdDgQWBBScqgRdXu0dHmlwwuoKQqppJ/k/djAfBgNVHSMEGDAWgBT5j1fm/9BC
#  IkHCN21mQH1beD4rxTANBgkqhkiG9w0BAQsFAAOCAgEAx7MhyY4qCXiHcinV9TE8
#  W6Dl791n9TqOwS3EH2QEmgy2gPIZ9m5mmsewwQFO/iO5vj2z8Rvimwuzrg6ABk8e
#  gl0/kk+fN2XkwaUIrqJNI82EOjOHTxFgew632Bo8bS72s/Xg8Yx+Bh+9K+KHUJWJ
#  BWaHhMbCisK6VOH75AkLVQzAHQ6g1aPr801/tBGflWgElOqvRFtooEbdpNAG6Sxv
#  UnQv2eUCtwTX8UivFI8QeZlnVZ/cyLDqlrja8wljTXF+cZPURmEby2GX3pRUxbsL
#  LOhTzzItgb2kUaeWJEII/AgQaYj2Jfp3qlj/WvnQXyLTk/JIRlPwpttatMsCvfyP
#  ARd3lah7sDCbLua2QICuZl9Avv4PUaO0xp4C+O3/hggcWqJTv4Tf5Zp2/MDjHuGM
#  wQ+EZGW+fNulT3sdcl/kVi9WqfnqI6J2DLN/2kAUhjW2H+vjQJHF12OAytktTYaW
#  hJuResd5O3Bl/cuvLvksdOEv9uQFmQRhPwqAzK2kUP4NAt4qa7fuZlbb5GSEyqzw
#  lumKmCFY0yA4Xra2x9smM+dR1/iuPgY80gX9/OA37v4gQrXRo0eH/JEgpK9l+cFB
#  Ixjhv9LPUvnaDXwK4H8WywLa3+fkkji2B2IgA6I/zaf9tliDrv2rDOq58D53P0Cg
#  495uDWkW3B8Jo5CTmm/wFgU=
#  -----END CERTIFICATE-----
#


resources:
  peer:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  couchdb:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  chaincode:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
replicas: 1
nodeSelector: { }

tolerations: [ ]

affinity: { }


externalHost: peer0:443
fullnameOverride: peer0
hostAliases: [ ]
service:
  type: NodePort
  portRequest: 7051
  portEvent: 7053
  portOperations: 9443

persistence:
  peer:
    enabled: true
    annotations: { }
    storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
  couchdb:
    enabled: true
    annotations: { }
    storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
  chaincode:
    enabled: true
    annotations: { }
    storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
logging:
  level: debug
  peer: debug
  cauthdsl: warning
  gossip: debug
  grpc: error
  ledger: debug
  msp: debug
  policies: warning

externalChaincodeBuilder: false

externalBuilders: [ ]


serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: false
  #  namespace: monitoring
  labels: { }
  interval: 10s
  scrapeTimeout: 10s
  scheme: http
  relabelings: [ ]
  targetLabels: [ ]
  metricRelabelings: [ ]
  sampleLimit: 0

