apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  creationTimestamp: null
  name: org1-peer0
  namespace: default
spec:
  couchdb:
    password: couchdb
    user: couchdb
  discovery:
    period: 60s
    touchPeriod: 60s
  dockerSocketPath: /var/run/docker.sock
  external_chaincode_builder: true
  externalEndpoint: ""
  gossip:
    bootstrap: ""
    endpoint: ""
    externalEndpoint: ""
    orgLeader: false
    useLeaderElection: true
  hosts: []
  image: quay.io/kfsoftware/fabric-peer
  istio:
    hosts:omitempty: []
    port: 443
  logging:
    cauthdsl: info
    gossip: info
    grpc: info
    ledger: info
    level: info
    msp: info
    peer: info
    policies: info
  mspID: Org1MSP
  operationHosts: []
  operationIPs: []
  resources:
    chaincode:
      limits:
        cpu: "2"
        memory: 4096M
      requests:
        cpu: 10m
        memory: 10M
    couchdb:
      limits:
        cpu: "2"
        memory: 4096M
      requests:
        cpu: 10m
        memory: 10M
    peer:
      limits:
        cpu: "2"
        memory: 4096M
      requests:
        cpu: 10m
        memory: 10M
  secret:
    enrollment:
      component:
        cahost: 172.18.0.2
        caname: ca
        caport: 30125
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUVENDQWZPZ0F3SUJBZ0lRTFF4TGxsdWkyWGpNakp5MWhPVm8rakFLQmdncWhrak9QUVFEQWpCU01STXcKRVFZRFZRUUdFd3BEWVd4cFptOXlibWxoTVFrd0J3WURWUVFIRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRQpDaE1MU0hsd1pYSnNaV1JuWlhJeER6QU5CZ05WQkFzVEJrWmhZbkpwWXpBZUZ3MHlNVEF5TURjeE1UVTVNRFphCkZ3MHpNVEF5TURneE1UVTVNRFphTUZJeEV6QVJCZ05WQkFZVENrTmhiR2xtYjNKdWFXRXhDVEFIQmdOVkJBY1QKQURFSk1BY0dBMVVFQ1JNQU1SUXdFZ1lEVlFRS0V3dEllWEJsY214bFpHZGxjakVQTUEwR0ExVUVDeE1HUm1GaQpjbWxqTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbWZXVm4zbjFqQjdFdGVJTjMzbkxpMFpZCldadzhsSlFMTkRKUzdTbWlRWkZXd2l0WVBXdGJacHNKK3o2ZUpRNVQ3clg4Nm1EMlZrekJJVmRsTGduTW5LT0IKcWpDQnB6QU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRgpCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3S1FZRFZSME9CQ0lFSVBnWGhkeVBMSnNiWld1ZUpkMGsxMlJBCnE3dWRGWVVYVWZCNU9aSDhYVm1iTURvR0ExVWRFUVF6TURHQ0NXeHZZMkZzYUc5emRJSUhiM0puTVMxallZSVAKYjNKbk1TMWpZUzVrWldaaGRXeDBod1IvQUFBQmh3U3NFZ0FDTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDSApGQXNkamtjZjZiZkFSMExibGQ4a1podU9FMnhaZDMzZDQ4STB0TSt3b0FJZ052MkRoV0syMkxDb2F3MStZQ0wxClBidzlNTnU4RjlzY1NRbHZZOG9rSEtFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        enrollid: peer
        enrollsecret: peerpw
      tls:
        cahost: 172.18.0.2
        caname: tlsca
        caport: 30125
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUVENDQWZPZ0F3SUJBZ0lRTFF4TGxsdWkyWGpNakp5MWhPVm8rakFLQmdncWhrak9QUVFEQWpCU01STXcKRVFZRFZRUUdFd3BEWVd4cFptOXlibWxoTVFrd0J3WURWUVFIRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRQpDaE1MU0hsd1pYSnNaV1JuWlhJeER6QU5CZ05WQkFzVEJrWmhZbkpwWXpBZUZ3MHlNVEF5TURjeE1UVTVNRFphCkZ3MHpNVEF5TURneE1UVTVNRFphTUZJeEV6QVJCZ05WQkFZVENrTmhiR2xtYjNKdWFXRXhDVEFIQmdOVkJBY1QKQURFSk1BY0dBMVVFQ1JNQU1SUXdFZ1lEVlFRS0V3dEllWEJsY214bFpHZGxjakVQTUEwR0ExVUVDeE1HUm1GaQpjbWxqTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbWZXVm4zbjFqQjdFdGVJTjMzbkxpMFpZCldadzhsSlFMTkRKUzdTbWlRWkZXd2l0WVBXdGJacHNKK3o2ZUpRNVQ3clg4Nm1EMlZrekJJVmRsTGduTW5LT0IKcWpDQnB6QU9CZ05WSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRgpCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3S1FZRFZSME9CQ0lFSVBnWGhkeVBMSnNiWld1ZUpkMGsxMlJBCnE3dWRGWVVYVWZCNU9aSDhYVm1iTURvR0ExVWRFUVF6TURHQ0NXeHZZMkZzYUc5emRJSUhiM0puTVMxallZSVAKYjNKbk1TMWpZUzVrWldaaGRXeDBod1IvQUFBQmh3U3NFZ0FDTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDSApGQXNkamtjZjZiZkFSMExibGQ4a1podU9FMnhaZDMzZDQ4STB0TSt3b0FJZ052MkRoV0syMkxDb2F3MStZQ0wxClBidzlNTnU4RjlzY1NRbHZZOG9rSEtFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        csr:
          cn: ""
          hosts:
          - 127.0.0.1
          - localhost
          - 172.18.0.2
        enrollid: peer
        enrollsecret: peerpw
  service:
    type: NodePort
  stateDb: leveldb
  storage:
    chaincode:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: standard
    couchdb:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: standard
    peer:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: standard
  tag: amd64-2.2.0

