name: goreleaser beta

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'

permissions:
    contents: write # for goreleaser to create releases
    packages: write # for pushing to ghcr.io
    id-token: write # for signing the images

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.23
            - name: Docker Login
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v2
              with:
                  version: latest
                  args: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
